
spring:
  application:
    name: geolocator
  datasource:
    url: jdbc:postgresql://localhost:5432/geo
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver


server:
  port: 8000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    region: default
    registryFetchIntervalSeconds: 5